// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package openapi

// Coininvestment defines model for coininvestment.
type Coininvestment struct {
	Current *Investment `json:"current,omitempty"`
	Symbol  *string     `json:"symbol,omitempty"`
}

// Current defines model for current.
type Current struct {
	Amount  *string `json:"amount,omitempty"`
	Balance *string `json:"balance,omitempty"`
	Price   *string `json:"price,omitempty"`
}

// Data defines model for data.
type Data struct {
	Current *Current `json:"current,omitempty"`
	Symbol  *string  `json:"symbol,omitempty"`
}

// Detail defines model for detail.
type Detail struct {
	Datas *[]Data `json:"datas,omitempty"`
}

// Investment defines model for investment.
type Investment struct {
	Deposit  *string `json:"deposit,omitempty"`
	Withdraw *string `json:"withdraw,omitempty"`
}

// Message defines model for message.
type Message struct {
	Message *string `json:"message,omitempty"`
}

// Myinvestment defines model for myinvestment.
type Myinvestment struct {
	Datas *[]Coininvestment `json:"datas,omitempty"`
}

// PostApiInvestmentJSONRequestBody defines body for PostApiInvestment for application/json ContentType.
type PostApiInvestmentJSONRequestBody = Myinvestment
