// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package openapi

// Current defines model for current.
type Current struct {
	Amount  *string `json:"amount,omitempty"`
	Balance *string `json:"balance,omitempty"`
	Price   *string `json:"price,omitempty"`
}

// Data defines model for data.
type Data struct {
	Current *Current `json:"current,omitempty"`
	Symbol  *string  `json:"symbol,omitempty"`
}

// Detail defines model for detail.
type Detail struct {
	Datas *[]Data `json:"datas,omitempty"`
}

// Message defines model for message.
type Message struct {
	Message *string `json:"message,omitempty"`
}

// PostApiHistoryJSONRequestBody defines body for PostApiHistory for application/json ContentType.
type PostApiHistoryJSONRequestBody = Detail
