// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package openapi

// Detail defines model for detail.
type Detail struct {
	Datas *[]struct {
		Current *struct {
			Amount  *string `json:"amount,omitempty"`
			Balance *string `json:"balance,omitempty"`
			Price   *string `json:"price,omitempty"`
		} `json:"current,omitempty"`
		Symbol *string `json:"symbol,omitempty"`
	} `json:"datas,omitempty"`
}
